version: "3"
services:
  jupyter:
    build: .
    ports:
      - "80:8888"
    volumes:
      - ".:/usr/src/app"

  mongo:
    image: mongo:jessie
    volumes:
      - ${DATA_SAVE_PATH}/mongo:/data/db

  redis:
    image: redis:4-alpine
    volumes:
      - ${DATA_SAVE_PATH}/redis:/data

  mecab:
    build: ./docker/mecab/

  corenlp:
    build: ./docker/corenlp